# Generated by Django 3.0.2 on 2020-02-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=20, verbose_name='路径')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('icon', models.CharField(blank=True, max_length=10, null=True, verbose_name='图标')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserMenu', verbose_name='父级菜单')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Permission', verbose_name='关联权限')),
            ],
            options={
                'verbose_name': '用户菜单',
                'verbose_name_plural': '用户菜单',
            },
        ),
    ]
