# Generated by Django 3.0.2 on 2020-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='path',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='路径'),
        ),
    ]
