# Generated by Django 3.0.2 on 2020-02-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200209_2022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermenu',
            table='users_menu',
        ),
    ]
